# Change these first
owner: artemislena # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Main site
    url: https://artemislena.eu
  - name: GTRR
    url: https://gtrr.artemislena.eu
  - name: BorgBackup
    check: "tcp-ping"
    url: borg.artemislena.eu
    port: 2222
  - name: Matrix (client)
    url: https://matrix.artemislena.eu
  - name: Matrix (server)
    url: https://matrix.artemislena.eu:8448/_matrix/static
  - name: Whoareyou
    url: https://artemislena.eu/services/whoareyou.html
  - name: Plik
    url: https://plik.artemislena.eu
  - name: Teddit
    url: https://teddit.artemislena.eu
  - name: Invidious
    url: https://yt.artemislena.eu
  - name: Nitter
    url: https://tw.artemislena.eu
  - name: Rimgo
    url: https://imgur.artemislena.eu
  - name: CryptPad
    url: https://pad.artemislena.eu
  - name: Ntfy
    url: https://ntfy.artemislena.eu
  - name: Mailcow (web)
    url: https://mail.artemislena.eu
  - name: Mailcow (SMTP)
    check: "tcp-ping"
    url: mail.artemislena.eu
    port: 25
  - name: Croc
    check: "tcp-ping"
    url: croc.artemislena.eu
    port: 9009
  - name: BreezeWiki
    url: https://bw.artemislena.eu
  - name: Libreddit
    url: https://lr.artemislena.eu

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.artemislena.eu
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Status page for [artemislena.eu](https://artemislena.eu)"
  introMessage: "This monitors the uptime for services hosted on `artemislena.eu`. Hosted on GitHub, not our own servers."
  navbar:
    - title: artemislena.eu
      href: https://artemislena.eu
    - title: GitHub repo
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
    uptime: "*/10 * * * *"

userAgent: artemislena
